[phases.setup]
nixPkgs = ["ffmpeg"]
aptPkgs = [
  "libxcb1",
  "libx11-6",
  "libxext6",
  "libgl1",
  "libglib2.0-0",
  "libsm6",
  "libxrender1"
]

[variables]
NIXPACKS_PYTHON_VERSION = "3.12"
QT_QPA_PLATFORM = "offscreen"
DISPLAY = ""
OPENCV_IO_ENABLE_OPENEXR = "0"
MPLBACKEND = "Agg"
