"""
Social OAuth2 endpoints — YouTube and TikTok.

Security measures applied:
  - CSRF protection: signed state stored in Redis (10-min TTL), verified on callback
  - Exception leakage prevented: internal errors are logged, clients receive generic messages
  - Structured logging: every step carries request_id and user_id
"""
import logging
from urllib.parse import parse_qs, urlparse

import redis.asyncio as aioredis
from fastapi import APIRouter, Depends, HTTPException, Request

from app.config import settings
from app.dependencies import get_current_user
from app.integrations.tiktok import tiktok_service
from app.integrations.youtube import youtube_service

logger = logging.getLogger(__name__)
router = APIRouter()

# ---------------------------------------------------------------------------
# Redis singleton — reuses the same pattern as auth_service
# ---------------------------------------------------------------------------

_redis: aioredis.Redis | None = None


def _get_redis() -> aioredis.Redis:
    global _redis
    if _redis is None:
        _redis = aioredis.from_url(
            settings.REDIS_URL, encoding="utf-8", decode_responses=True
        )
    return _redis


def _request_id(request: Request) -> str:
    return getattr(request.state, "request_id", "unknown")


_OAUTH_STATE_TTL = 600  # 10 minutes


# ---------------------------------------------------------------------------
# YouTube OAuth
# ---------------------------------------------------------------------------

@router.get("/auth/youtube/url", summary="Get YouTube OAuth2 authorisation URL")
async def get_youtube_auth_url(
    request: Request,
    current_user=Depends(get_current_user),
):
    rid = _request_id(request)
    logger.info(
        "YouTube auth URL requested | id=%s | user=%s", rid, current_user.id
    )

    url = youtube_service.get_auth_url(str(current_user.id))

    # Extract state generated by the service and store it in Redis for CSRF check
    parsed = urlparse(url)
    state = parse_qs(parsed.query).get("state", [None])[0]
    if state:
        r = _get_redis()
        await r.set(f"oauth:state:{state}", str(current_user.id), ex=_OAUTH_STATE_TTL)
        logger.info(
            "YouTube OAuth state stored | id=%s | user=%s | state_suffix=...%s",
            rid, current_user.id, state[-8:],
        )

    return {"status": "success", "data": {"url": url}}


@router.get("/auth/youtube/callback", summary="YouTube OAuth2 callback")
async def youtube_callback(
    request: Request,
    code: str,
    state: str = None,
):
    rid = _request_id(request)
    logger.info("YouTube OAuth callback received | id=%s", rid)

    # CSRF — state must be present
    if not state:
        logger.warning("YouTube OAuth callback: missing state | id=%s", rid)
        raise HTTPException(
            status_code=400,
            detail="Invalid OAuth state. Please restart the login flow.",
        )

    # CSRF — state must exist in Redis (proves it was issued by us)
    r = _get_redis()
    key = f"oauth:state:{state}"
    stored_user_id = await r.get(key)
    if not stored_user_id:
        logger.warning(
            "YouTube OAuth callback: invalid/expired state | id=%s | state_suffix=...%s",
            rid, state[-8:],
        )
        raise HTTPException(
            status_code=400,
            detail="OAuth session expired or invalid. Please restart the login flow.",
        )

    # Consume the state — one-time use
    await r.delete(key)

    try:
        tokens = youtube_service.handle_callback(code, state)
        logger.info(
            "YouTube OAuth callback succeeded | id=%s | user=%s", rid, stored_user_id
        )
        return {"status": "success", "data": tokens}
    except Exception as exc:
        logger.error(
            "YouTube OAuth callback failed | id=%s | user=%s | error=%s",
            rid, stored_user_id, exc,
        )
        raise HTTPException(
            status_code=400,
            detail="Authentication failed. Please try again.",
        )


# ---------------------------------------------------------------------------
# TikTok OAuth
# ---------------------------------------------------------------------------

@router.get("/auth/tiktok/url", summary="Get TikTok OAuth2 authorisation URL")
async def get_tiktok_auth_url(
    request: Request,
    current_user=Depends(get_current_user),
):
    rid = _request_id(request)
    logger.info(
        "TikTok auth URL requested | id=%s | user=%s", rid, current_user.id
    )

    url = tiktok_service.get_auth_url(str(current_user.id))

    # Extract state and store in Redis for CSRF check
    parsed = urlparse(url)
    state = parse_qs(parsed.query).get("state", [None])[0]
    if state:
        r = _get_redis()
        await r.set(f"oauth:state:{state}", str(current_user.id), ex=_OAUTH_STATE_TTL)
        logger.info(
            "TikTok OAuth state stored | id=%s | user=%s | state_suffix=...%s",
            rid, current_user.id, state[-8:],
        )

    return {"status": "success", "data": {"url": url}}


@router.get("/auth/tiktok/callback", summary="TikTok OAuth2 callback")
async def tiktok_callback(
    request: Request,
    code: str,
    state: str = None,
):
    rid = _request_id(request)
    logger.info("TikTok OAuth callback received | id=%s", rid)

    # CSRF — state must be present
    if not state:
        logger.warning("TikTok OAuth callback: missing state | id=%s", rid)
        raise HTTPException(
            status_code=400,
            detail="Invalid OAuth state. Please restart the login flow.",
        )

    # CSRF — state must exist in Redis
    r = _get_redis()
    key = f"oauth:state:{state}"
    stored_user_id = await r.get(key)
    if not stored_user_id:
        logger.warning(
            "TikTok OAuth callback: invalid/expired state | id=%s | state_suffix=...%s",
            rid, state[-8:],
        )
        raise HTTPException(
            status_code=400,
            detail="OAuth session expired or invalid. Please restart the login flow.",
        )

    # Consume the state — one-time use
    await r.delete(key)

    try:
        tokens = tiktok_service.handle_callback(code)
        logger.info(
            "TikTok OAuth callback succeeded | id=%s | user=%s", rid, stored_user_id
        )
        return {"status": "success", "data": tokens}
    except Exception as exc:
        logger.error(
            "TikTok OAuth callback failed | id=%s | user=%s | error=%s",
            rid, stored_user_id, exc,
        )
        raise HTTPException(
            status_code=400,
            detail="Authentication failed. Please try again.",
        )
