"""create_all_tables

Revision ID: 57026aafba41
Revises: 
Create Date: 2026-04-07 11:22:46.860861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57026aafba41'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('profile_picture_url', sa.Text(), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('public_profile_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ix_users_email_active', 'users', ['email', 'is_active'], unique=False)
    op.create_table('coaches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('rating', sa.Float(), server_default='0.0', nullable=False),
    sa.Column('submissions_completed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index('ix_coaches_is_active', 'coaches', ['is_active'], unique=False)
    op.create_index('ix_coaches_rating', 'coaches', ['rating'], unique=False)
    op.create_index('ix_coaches_user_id', 'coaches', ['user_id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('coach_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'UPLOADING', 'ANALYZING', 'READY_FOR_REVIEW', 'IN_REVIEW', 'CORRECTIONS_MADE', 'COMPLETED', 'REJECTED', name='submissionstatus'), server_default='PENDING', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_coach_id'), 'submissions', ['coach_id'], unique=False)
    op.create_index('ix_submissions_coach_status', 'submissions', ['coach_id', 'status'], unique=False)
    op.create_index('ix_submissions_created_at', 'submissions', ['created_at'], unique=False)
    op.create_index(op.f('ix_submissions_status'), 'submissions', ['status'], unique=False)
    op.create_index(op.f('ix_submissions_user_id'), 'submissions', ['user_id'], unique=False)
    op.create_index('ix_submissions_user_status', 'submissions', ['user_id', 'status'], unique=False)
    op.create_table('avatars',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('skeleton_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('avatar_obj_url', sa.Text(), nullable=True),
    sa.Column('avatar_fbx_url', sa.Text(), nullable=True),
    sa.Column('avatar_glb_url', sa.Text(), nullable=True),
    sa.Column('view_top_url', sa.Text(), nullable=True),
    sa.Column('view_front_url', sa.Text(), nullable=True),
    sa.Column('view_left_url', sa.Text(), nullable=True),
    sa.Column('view_right_url', sa.Text(), nullable=True),
    sa.Column('view_back_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='avatarstatus'), server_default='PENDING', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id')
    )
    op.create_index('ix_avatars_status', 'avatars', ['status'], unique=False)
    op.create_index('ix_avatars_submission_id', 'avatars', ['submission_id'], unique=False)
    op.create_table('coach_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('coach_id', sa.UUID(), nullable=False),
    sa.Column('notes_text', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('corrected_skeleton_json', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('auto_saved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['coaches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id')
    )
    op.create_index(op.f('ix_coach_notes_coach_id'), 'coach_notes', ['coach_id'], unique=False)
    op.create_index('ix_coach_notes_submission_id', 'coach_notes', ['submission_id'], unique=False)
    op.create_table('corrected_videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('angle', sa.Enum('TOP', 'FRONT', 'LEFT', 'RIGHT', 'BACK', name='correctionangle'), nullable=False),
    sa.Column('video_url', sa.Text(), nullable=False),
    sa.Column('b2_file_id', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_corrected_videos_submission_angle', 'corrected_videos', ['submission_id', 'angle'], unique=False)
    op.create_index(op.f('ix_corrected_videos_submission_id'), 'corrected_videos', ['submission_id'], unique=False)
    op.create_table('discount_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('discount_percent', sa.Integer(), server_default='15', nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discount_codes_code'), 'discount_codes', ['code'], unique=True)
    op.create_index('ix_discount_codes_code_used', 'discount_codes', ['code', 'used'], unique=False)
    op.create_index(op.f('ix_discount_codes_submission_id'), 'discount_codes', ['submission_id'], unique=False)
    op.create_index('ix_discount_codes_user_id', 'discount_codes', ['user_id'], unique=False)
    op.create_index('ix_discount_codes_valid_until', 'discount_codes', ['valid_until'], unique=False)
    op.create_table('results_videos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('video_url', sa.Text(), nullable=False),
    sa.Column('b2_file_id', sa.Text(), nullable=False),
    sa.Column('face_privacy', sa.Enum('SHOW', 'BLUR', 'COVER', name='faceprivacy'), server_default='SHOW', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_results_videos_submission_id'), 'results_videos', ['submission_id'], unique=False)
    op.create_table('social_sharings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('platforms', postgresql.JSON(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('opt_in', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('youtube_url', sa.Text(), nullable=True),
    sa.Column('tiktok_url', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id')
    )
    op.create_index('ix_social_sharings_opt_in', 'social_sharings', ['opt_in'], unique=False)
    op.create_index('ix_social_sharings_submission_id', 'social_sharings', ['submission_id'], unique=False)
    op.create_index(op.f('ix_social_sharings_user_id'), 'social_sharings', ['user_id'], unique=False)
    op.create_table('submission_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('file_type', sa.Enum('FRONT_IMAGE', 'LEFT_IMAGE', 'RIGHT_IMAGE', 'BACK_IMAGE', 'SWING_VIDEO', name='filetype'), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('b2_file_id', sa.Text(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_submission_files_submission_id', 'submission_files', ['submission_id'], unique=False)
    op.create_index('ix_submission_files_submission_type', 'submission_files', ['submission_id', 'file_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_submission_files_submission_type', table_name='submission_files')
    op.drop_index('ix_submission_files_submission_id', table_name='submission_files')
    op.drop_table('submission_files')
    op.drop_index(op.f('ix_social_sharings_user_id'), table_name='social_sharings')
    op.drop_index('ix_social_sharings_submission_id', table_name='social_sharings')
    op.drop_index('ix_social_sharings_opt_in', table_name='social_sharings')
    op.drop_table('social_sharings')
    op.drop_index(op.f('ix_results_videos_submission_id'), table_name='results_videos')
    op.drop_table('results_videos')
    op.drop_index('ix_discount_codes_valid_until', table_name='discount_codes')
    op.drop_index('ix_discount_codes_user_id', table_name='discount_codes')
    op.drop_index(op.f('ix_discount_codes_submission_id'), table_name='discount_codes')
    op.drop_index('ix_discount_codes_code_used', table_name='discount_codes')
    op.drop_index(op.f('ix_discount_codes_code'), table_name='discount_codes')
    op.drop_table('discount_codes')
    op.drop_index(op.f('ix_corrected_videos_submission_id'), table_name='corrected_videos')
    op.drop_index('ix_corrected_videos_submission_angle', table_name='corrected_videos')
    op.drop_table('corrected_videos')
    op.drop_index('ix_coach_notes_submission_id', table_name='coach_notes')
    op.drop_index(op.f('ix_coach_notes_coach_id'), table_name='coach_notes')
    op.drop_table('coach_notes')
    op.drop_index('ix_avatars_submission_id', table_name='avatars')
    op.drop_index('ix_avatars_status', table_name='avatars')
    op.drop_table('avatars')
    op.drop_index('ix_submissions_user_status', table_name='submissions')
    op.drop_index(op.f('ix_submissions_user_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_status'), table_name='submissions')
    op.drop_index('ix_submissions_created_at', table_name='submissions')
    op.drop_index('ix_submissions_coach_status', table_name='submissions')
    op.drop_index(op.f('ix_submissions_coach_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index('ix_coaches_user_id', table_name='coaches')
    op.drop_index('ix_coaches_rating', table_name='coaches')
    op.drop_index('ix_coaches_is_active', table_name='coaches')
    op.drop_table('coaches')
    op.drop_index('ix_users_email_active', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('ix_users_created_at', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
